In [1]:
import pandas as pd
import numpy as np
import os 
import matplotlib.pyplot as plt
import turicreate as tc

/home/po/anaconda3/envs/Py_ml_ud/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/po/anaconda3/envs/Py_ml_ud/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/po/anaconda3/envs/Py_ml_ud/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/po/anaconda3/envs/Py_ml_ud/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/po/anaconda3/envs/Py_ml_ud/lib/python3.6/importlib/_bootstrap.py:219: 

In [2]:
os.chdir("/home/po/projects/flood_classification")

In [4]:
os.getcwd()

'/home/po/projects/flood_classification'

In [5]:
data = pd.read_csv(os.path.join("data","filt_data.csv"))

In [8]:
data

gx       gy       gz       ax       ay       az       wx       wy  \
0      1.01600  9.61500  1.63700 -0.46600 -1.91300 -1.02200  0.02900 -0.23100   
1      0.69400  9.64500  1.63200 -0.94100 -2.20800 -0.31700 -0.05400  0.36400   
2      0.84000  9.62500  1.68300  0.64200 -1.15400 -1.06800 -0.14300 -0.57800   
3      0.85500  9.66800  1.40300  1.52700  1.57500 -1.18500  0.23200  0.16000   
4      0.52100  9.73400  1.07500 -0.15400  4.81600 -0.19800  0.05800 -0.15800   
...        ...      ...      ...      ...      ...      ...      ...      ...   
22593  0.65943  4.70249  8.58034  0.25970  0.00449  0.62383 -0.07692 -0.06419   
22594  0.50070  4.43200  8.73368  1.11125 -0.70083  1.84900 -0.56322 -0.21066   
22595  0.21700  4.59765  8.65938  0.15993 -0.60136  0.55145  0.50471  0.01837   
22596  0.16437  4.88976  8.49904  0.70071 -0.50386 -0.53511  0.50206 -0.36832   
22597  0.12494  5.49104  8.12424  0.15885  0.46833 -1.05965  0.87117 -0.43916   

            wz  label  
0     -0.53300    0.0  
1     -0.09500    0.0  
2      0.18500    0.0  
3     -0.53100    0.0  
4      0.07800    0.0  
...        ...    ...  
22593 -0.16707    2.5  
22594 -0.68532    2.5  
22595 -0.09995    2.5  
22596 -0.29810    2.5  
22597 -0.19795    2.5  

[22598 rows x 10 columns]

In [15]:
# creating the first window
win = data.iloc[0:50,:-1]

In [16]:
win

gx     gy     gz     ax     ay     az     wx     wy     wz
0   1.016  9.615  1.637 -0.466 -1.913 -1.022  0.029 -0.231 -0.533
1   0.694  9.645  1.632 -0.941 -2.208 -0.317 -0.054  0.364 -0.095
2   0.840  9.625  1.683  0.642 -1.154 -1.068 -0.143 -0.578  0.185
3   0.855  9.668  1.403  1.527  1.575 -1.185  0.232  0.160 -0.531
4   0.521  9.734  1.075 -0.154  4.816 -0.198  0.058 -0.158  0.078
5   0.743  9.715  1.116 -0.438  0.844  0.395  0.011 -0.511  0.337
6   0.943  9.640  1.535  0.276 -3.139  0.795 -0.189  0.126 -0.229
7   0.697  9.708  1.201 -0.311 -3.011 -1.347  0.364 -0.453  0.019
8   0.752  9.719  1.066 -0.539 -0.897 -1.950 -0.021 -0.125  0.061
9   0.801  9.716  1.063 -0.425  3.984  1.906 -0.118 -0.585  0.099
10  1.065  9.702  0.952  0.137  2.976  0.315  0.115 -0.104  0.280
11  1.269  9.698  0.716  0.774 -0.549 -1.130 -0.375 -0.555 -0.076
12  1.131  9.688  1.014 -0.808 -2.805  1.335  0.216  0.343 -0.320
13  0.943  9.713  0.973 -1.280 -1.270 -0.958 -0.451 -0.147  0.287
14  1.270  9.639  1.287  0.205 -0.047 -1.356 -0.554 -0.361  0.178
15  1.277  9.626  1.373  0.322  1.587  1.543  0.309  0.346 -0.266
16  1.066  9.694  1.026  0.780  2.176  0.200  0.149 -0.198 -0.026
17  1.009  9.709  0.945 -0.394  0.592  1.267  0.092  0.080 -0.074
18  1.022  9.658  1.359 -0.567 -1.920  1.272 -0.068 -0.045 -0.023
19  0.828  9.671  1.396  0.115 -2.670 -1.636 -0.201 -0.207 -0.405
20  0.670  9.704  1.246 -0.644 -0.366 -0.604  0.157  0.114 -0.009
21  0.694  9.726  1.041 -0.055  1.759 -0.115  0.095  0.417  0.079
22  0.527  9.766  0.715 -0.096  3.572 -0.670 -0.093 -0.023  0.200
23  0.670  9.757  0.723  0.525  0.543  0.151  0.343 -0.373  0.034
24  0.771  9.725  0.995 -1.252 -1.870  1.885  0.010  0.294  0.063
25  0.818  9.712  1.081  0.233 -2.204 -1.388 -0.228  0.149  0.067
26  0.676  9.711  1.191 -0.059 -0.725  0.184  0.066  0.204 -0.101
27  0.547  9.713  1.238  0.274  1.030 -0.194 -0.078  0.255 -0.156
28  0.372  9.744  1.042  0.401  2.587 -0.659  0.201 -0.117 -0.172
29  0.410  9.725  1.194  0.658  1.066  0.420 -0.592  0.115 -0.055
30  0.263  9.701  1.413 -1.154 -0.557  0.284  0.047 -0.632 -0.034
31  0.331  9.693  1.449 -0.128 -1.206 -1.420  0.053 -0.007  0.169
32  0.467  9.702  1.349 -0.326 -0.910 -0.283  0.035  0.006  0.047
33  0.420  9.742  1.045  0.251  0.764 -0.698  0.557 -0.075 -0.118
34  0.351  9.781  0.612  0.276  1.448  0.669  0.350 -0.119 -0.033
35  0.327  9.784  0.588  0.602  1.810  0.866 -0.139  0.078  0.035
36  0.307  9.784  0.588  1.287  0.693 -0.667 -0.310 -0.551  0.109
37  0.488  9.753  0.905  0.041 -1.236  1.511  0.077  0.147 -0.167
38  0.433  9.749  0.965  0.015 -1.975 -1.242 -0.016 -0.509 -0.052
39  0.387  9.754  0.941  0.510 -1.505 -1.295 -0.200 -0.029 -0.065
40  0.240  9.757  0.953  0.227  2.027 -1.088 -0.330 -0.214 -0.177
41  0.097  9.739  1.147  0.391  3.044 -0.235 -0.291 -0.121 -0.119
42 -0.158  9.719  1.297 -1.626  0.990  2.889  0.769  0.864 -0.335
43 -0.154  9.745  1.087  0.101 -0.977 -1.305 -0.710 -0.492  0.561
44  0.092  9.694  1.482  0.107 -1.654 -0.172 -0.030  0.140 -0.062
45  0.234  9.677  1.571  0.340 -0.555 -0.867 -0.064 -0.143  0.178
46  0.263  9.694  1.460 -0.134  1.358 -0.172  0.292 -0.269 -0.081
47  0.391  9.729  1.167  0.617  2.850  0.093  0.077 -0.279  0.082
48  0.714  9.694  1.298  0.241 -0.447  1.659  0.175 -0.746  0.144
49  0.641  9.734  1.000  0.187  0.125 -1.459  0.070  0.158 -0.247

In [37]:
def cal_fft(df):
    return np.fft.rfft(df)

In [38]:
win.iloc[:,0].mean()

0.62062

In [20]:
fft_1 = cal_fft(win.iloc[:,0])

In [21]:
fft_1

array([31.031      +0.j        , -0.93992512-10.31474236j,
       -0.7884205  -1.13077764j,  2.86736434 -0.0144209j ,
        3.90954376 -0.13989042j, -0.16006386 +0.97710014j,
        0.65385833 +0.63637935j, -1.42901987 -0.25532359j,
        0.95245622 -0.392108j  ,  0.85764308 +0.21175696j,
        0.80782158 -0.20315804j, -0.3645895  -0.76650734j,
       -0.84635891 +0.72044396j, -0.73974365 +1.00937973j,
        0.40393931 +0.0661829j , -0.30093614 -0.29895705j,
        0.21484923 +0.50231763j,  1.24606154 +0.37126088j,
        0.53841557 -0.35154001j,  0.86880834 -0.47363585j,
        0.30917842 -0.24121942j,  0.28406654 -0.31331223j,
        0.49786773 -0.45098737j,  0.18683431 -0.01826627j,
        0.75634925 +0.3182237j ,  0.197      +0.j        ])

In [22]:
len(fft_1)

26

 Sum of FFT Coefficients ::The first five coefficients
found using the FFT representing lower frequencies are
summed. A higher value of the sum of FFT coefficients
indicates a better frequency response at these lower
frequencies

In [24]:
fft_1[:5]

array([31.031      +0.j        , -0.93992512-10.31474236j,
       -0.7884205  -1.13077764j,  2.86736434 -0.0144209j ,
        3.90954376 -0.13989042j])

In [26]:
s = np.sum(fft_1[:5])

In [27]:
s

(36.079562483808836-11.599831323216j)

In [28]:
type(s)

numpy.complex128

In [67]:
#s.imag+s.real

testing using scipy.fftpack

In [45]:
import scipy.fftpack as fft

In [59]:
fft_2 = fft.rfft(win.iloc[:,0].values)

In [71]:
fft_2

array([ 3.10310000e+01, -9.39925119e-01, -1.03147424e+01, -7.88420502e-01,
       -1.13077764e+00,  2.86736434e+00, -1.44209032e-02,  3.90954376e+00,
       -1.39890424e-01, -1.60063859e-01,  9.77100139e-01,  6.53858332e-01,
        6.36379352e-01, -1.42901987e+00, -2.55323592e-01,  9.52456221e-01,
       -3.92107997e-01,  8.57643077e-01,  2.11756960e-01,  8.07821579e-01,
       -2.03158044e-01, -3.64589505e-01, -7.66507338e-01, -8.46358907e-01,
        7.20443965e-01, -7.39743652e-01,  1.00937973e+00,  4.03939314e-01,
        6.61828990e-02, -3.00936141e-01, -2.98957051e-01,  2.14849226e-01,
        5.02317626e-01,  1.24606154e+00,  3.71260877e-01,  5.38415567e-01,
       -3.51540009e-01,  8.68808337e-01, -4.73635851e-01,  3.09178421e-01,
       -2.41219421e-01,  2.84066543e-01, -3.13312232e-01,  4.97867735e-01,
       -4.50987374e-01,  1.86834308e-01, -1.82662734e-02,  7.56349251e-01,
        3.18223703e-01,  1.97000000e-01])

In [52]:
len(fft_2)

50

In [55]:
fft_2[:5]

array([ 31.031     ,  -0.93992512, -10.31474236,  -0.7884205 ,
        -1.13077764])

In [63]:
# compairing the fft_1 and fft_2

fft_1[:5]

array([31.031      +0.j        , -0.93992512-10.31474236j,
       -0.7884205  -1.13077764j,  2.86736434 -0.0144209j ,
        3.90954376 -0.13989042j])

In [64]:
fft_2[:5]

array([ 31.031     ,  -0.93992512, -10.31474236,  -0.7884205 ,
        -1.13077764])

In [65]:
np.sum(fft_1[:5])

(36.079562483808836-11.599831323216j)

In [66]:
np.sum(fft_2[:5])

17.85713438345656

Spectral Energy:>>> It is the sum of squared FFT coeffi-
cents normalized by length of the window.

