In [1]:
import numpy as np
import pandas as pd
import os
import scipy.fftpack as fftpack
import sklearn.preprocessing as preprocess
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB

In [2]:
os.getcwd()

'C:\\Users\\HP\\Documents\\projects\\flood_classification\\models'

In [3]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Sep 15 21:19:11 2020
"""

import numpy as np
import pandas as pd
import os
import scipy.fftpack as fftpack

# setting the root directory as the corrent working directory
os.chdir("C:\\Users\\HP\\Documents\\projects\\flood_classification")
data = pd.read_csv(os.path.join("data","filt_data.csv"))
'''
50 consecutive
readings when data is recorded at 10Hz, with an overlap
of 25 readings between consecutive examples

window_size = 50
overlap = 25

since overlap is set to 25 per window then total number of windows for 
a class c will be c/25

'''
def call_ftt(frame):
    fft = fftpack.fft(np.array(frame))
    amplitudes = np.abs(fft)
    coe = amplitudes[1:6]
    return np.sum(coe)


def energy(frame):
    fft = fftpack.fft(np.array(frame))
    amplitudes = np.abs(fft)
    coe = amplitudes[1:26]
    power = coe ** 2
    return np.sum(power)/25


labels = [0,0.19,4.5,2.5]

#creating an empty dataframe to store new data
a = np.zeros(shape=(902,46))
nd = pd.DataFrame(a, columns = [
        'gx_mean','gx_median','gx_variance','gx_fft','gx_spec_energy',
        'gy_mean','gy_median','gy_variance','gy_fft','gy_spec_energy',
        'gz_mean','gz_median','gz_variance','gz_fft','gz_spec_energy',
        'ax_mean','ax_median','ax_variance','ax_fft','ax_spec_energy',
        'ay_mean','ay_median','ay_variance','ay_fft','ay_spec_energy',
        'az_mean','az_median','az_variance','az_fft','az_spec_energy',
        'wx_mean','wx_median','wx_variance','wx_fft','wx_spec_energy',
        'wy_mean','wy_median','wy_variance','wy_fft','wy_spec_energy',
        'wz_mean','wz_median','wz_variance','wz_fft','wz_spec_energy',
        'label'
        ])

k = 0 # keeping the row index of the new dataFrame

# defining the functions to calculate the sum of coefficients of fft
# done above



# 
for l in labels:
    dl = data[data["label"]== l].iloc[:,:-1]
    row_max = dl.shape[0]
    # assigning the highest multiple of 50 less than row_max
    fn_row = row_max - row_max % 50
    i, j = 0, 50
    while(True):
        print(i,j,k)
#         print(k)
        
        for col in dl.columns:
            nd[col+"_mean"][k] = dl[col].iloc[i:j].mean()
            #print(nd[col+"_mean"][k] )
            nd[col+"_median"][k] = dl[col].iloc[i:j].median()
            nd[col+"_variance"][k] = dl[col].iloc[i:j].var()
            nd[col+"_fft"][k] = call_ftt(dl[col].iloc[i:j].values)
            nd[col+"_spec_energy"][k] = energy(dl[col].iloc[i:j].values)
#             print(np.array(dl[col].iloc[i:j]))
            nd['label'][k] = l
            
        
        i = i + 25
        j = j + 25
        k = k + 1
        if i >= fn_row:
            break
        
nd.to_csv(os.path.join("data","win_data_ext.csv"),index=False)

0 50 0
25 75 1
50 100 2
75 125 3
100 150 4
125 175 5
150 200 6
175 225 7
200 250 8
225 275 9
250 300 10
275 325 11
300 350 12
325 375 13
350 400 14
375 425 15
400 450 16
425 475 17
450 500 18
475 525 19
500 550 20
525 575 21
550 600 22
575 625 23
600 650 24
625 675 25
650 700 26
675 725 27
700 750 28
725 775 29
750 800 30
775 825 31
800 850 32
825 875 33
850 900 34
875 925 35
900 950 36
925 975 37
950 1000 38
975 1025 39
1000 1050 40
1025 1075 41
1050 1100 42
1075 1125 43
1100 1150 44
1125 1175 45
1150 1200 46
1175 1225 47
1200 1250 48
1225 1275 49
1250 1300 50
1275 1325 51
1300 1350 52
1325 1375 53
1350 1400 54
1375 1425 55
1400 1450 56
1425 1475 57
1450 1500 58
1475 1525 59
1500 1550 60
1525 1575 61
1550 1600 62
1575 1625 63
1600 1650 64
1625 1675 65
1650 1700 66
1675 1725 67
1700 1750 68
1725 1775 69
1750 1800 70
1775 1825 71
1800 1850 72
1825 1875 73
1850 1900 74
1875 1925 75
1900 1950 76
1925 1975 77
1950 2000 78
1975 2025 79
2000 2050 80
2025 2075 81
2050 2100 82
2075 2125 83
210

6600 6650 618
6625 6675 619
6650 6700 620
6675 6725 621
6700 6750 622
6725 6775 623
6750 6800 624
6775 6825 625
6800 6850 626
6825 6875 627
6850 6900 628
6875 6925 629
6900 6950 630
6925 6975 631
6950 7000 632
6975 7025 633
7000 7050 634
7025 7075 635
7050 7100 636
7075 7125 637
7100 7150 638
7125 7175 639
7150 7200 640
7175 7225 641
7200 7250 642
7225 7275 643
7250 7300 644
7275 7325 645
7300 7350 646
7325 7375 647
7350 7400 648
7375 7425 649
7400 7450 650
7425 7475 651
7450 7500 652
7475 7525 653
7500 7550 654
7525 7575 655
7550 7600 656
7575 7625 657
7600 7650 658
7625 7675 659
7650 7700 660
7675 7725 661
7700 7750 662
7725 7775 663
7750 7800 664
7775 7825 665
7800 7850 666
7825 7875 667
7850 7900 668
7875 7925 669
7900 7950 670
7925 7975 671
7950 8000 672
7975 8025 673
8000 8050 674
8025 8075 675
8050 8100 676
8075 8125 677
8100 8150 678
8125 8175 679
8150 8200 680
8175 8225 681
8200 8250 682
8225 8275 683
8250 8300 684
8275 8325 685
8300 8350 686
8325 8375 687
8350 8400 688
8375 8

# standardising

In [4]:
dP = pd.read_csv(os.path.join("data","win_data_ext.csv"))
dP['label'] = dP['label'].apply(lambda x: str(x))
features = dP.columns[:-1]
for i in features:
    dP[i] = preprocess.scale(dP[i])
dP.to_csv(os.path.join("data","std_data_ext.csv"),index=False)

# models

In [5]:
data = pd.read_csv(os.path.join("data","std_data_ext.csv"))

In [6]:
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].apply(lambda x: str(x)).values

In [7]:
import random
kf5sh = KFold(n_splits= 5, shuffle= True, random_state= 23)

# SVM

In [17]:
model_svm = (SVC(C=3.0, kernel='linear'))

In [18]:
# applying the 5 fold cross validation
i = 1
acc_svm = []
d0_pre =[]
d0_rec=[]
d0_f1 =  []
d19_pre = []
d19_rec =[]
d19_f1=[]
d25_pre =[]
d25_rec=[]
d25_f1=[]
d45_pre=[]
d45_rec =[]
d45_f1=[]
for train_index, test_index in kf5sh.split(x):
#     print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = x[train_index], x[test_index]
    Y_train, Y_test = y[train_index], y[test_index]
    model_svm.fit(X_train,Y_train)
    y_pred = model_svm.predict(X_test)
    print("________________ ** {} ** ____________________".format(i))
    print(confusion_matrix(Y_test,y_pred))
    print(classification_report(Y_test,y_pred))
    print(accuracy_score(Y_test, y_pred))
    acc_svm.append(accuracy_score(Y_test, y_pred))
    rep = classification_report(Y_test,y_pred)
    d0_pre.append(float(rep.split('\n')[2].split('      ')[2].strip()))
    d0_rec.append(float(rep.split('\n')[2].split('      ')[3].strip()))
    d0_f1.append(float(rep.split('\n')[2].split('      ')[4].strip()))
    d19_pre.append(float(rep.split('\n')[3].split('      ')[2].strip()))
    d19_rec.append(float(rep.split('\n')[3].split('      ')[3].strip()))
    d19_f1.append(float(rep.split('\n')[3].split('      ')[4].strip()))
    d25_pre.append(float(rep.split('\n')[4].split('      ')[2].strip()))
    d25_rec.append(float(rep.split('\n')[4].split('      ')[3].strip()))
    d25_f1.append(float(rep.split('\n')[4].split('      ')[4].strip()))
    d45_pre.append(float(rep.split('\n')[5].split('      ')[2].strip()))
    d45_rec.append(float(rep.split('\n')[5].split('      ')[3].strip()))
    d45_f1.append(float(rep.split('\n')[5].split('      ')[4].strip()))
    i = i+1
    
print("average accuracy :{}".format(np.average(acc_svm)))
print("\n\n classification_report average\n")
print('                    precision    recall    f1-score   \n\n         0.00       {:.4f}      {:.4f}      {:.4f}        \n         0.19       {:.4f}      {:.4f}      {:.4f}        \n         2.50       {:.4f}      {:.4f}      {:.4f}      \n         4.50       {:.4f}      {:.4f}      {:.4f}        \n\n'.
      format(np.average(d0_pre), np.average(d0_rec), np.average(d0_f1), np.average(d19_pre), np.average(d19_rec), np.average(d19_f1), np.average(d25_pre), np.average(d25_rec), np.average(d25_f1), np.average(d45_pre), np.average(d45_rec),np.average(d45_f1)))


________________ ** 1 ** ____________________
[[26  0  0  0]
 [ 0 48  0  0]
 [ 0  0 25  0]
 [ 0  0  0 82]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        26
        0.19       1.00      1.00      1.00        48
         2.5       1.00      1.00      1.00        25
         4.5       1.00      1.00      1.00        82

    accuracy                           1.00       181
   macro avg       1.00      1.00      1.00       181
weighted avg       1.00      1.00      1.00       181

1.0
________________ ** 2 ** ____________________
[[31  0  0  0]
 [ 0 40  0  0]
 [ 2  0 25  0]
 [ 0  0  0 83]]
              precision    recall  f1-score   support

         0.0       0.94      1.00      0.97        31
        0.19       1.00      1.00      1.00        40
         2.5       1.00      0.93      0.96        27
         4.5       1.00      1.00      1.00        83

    accuracy                           0.99       181
   macro avg       0.

# RANDOM FOREST

In [19]:
model_rf = RandomForestClassifier(n_estimators=30,criterion='entropy',max_depth=10,max_features='sqrt',max_leaf_nodes=None,min_samples_split=8, random_state=21)

In [20]:
# applying the 5 fold cross validation
i = 1
acc_rf = []
d0_pre =[]
d0_rec=[]
d0_f1 =  []
d19_pre = []
d19_rec =[]
d19_f1=[]
d25_pre =[]
d25_rec=[]
d25_f1=[]
d45_pre=[]
d45_rec =[]
d45_f1=[]
for train_index, test_index in kf5sh.split(x):
#     print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = x[train_index], x[test_index]
    Y_train, Y_test = y[train_index], y[test_index]
    model_rf.fit(X_train,Y_train)
    y_pred = model_rf.predict(X_test)
    print("________________ ** {} ** ____________________".format(i))
    print(confusion_matrix(Y_test,y_pred))
    print(classification_report(Y_test,y_pred))
    print(accuracy_score(Y_test, y_pred))
    acc_rf.append(accuracy_score(Y_test, y_pred))
    rep = classification_report(Y_test,y_pred)
    d0_pre.append(float(rep.split('\n')[2].split('      ')[2].strip()))
    d0_rec.append(float(rep.split('\n')[2].split('      ')[3].strip()))
    d0_f1.append(float(rep.split('\n')[2].split('      ')[4].strip()))
    d19_pre.append(float(rep.split('\n')[3].split('      ')[2].strip()))
    d19_rec.append(float(rep.split('\n')[3].split('      ')[3].strip()))
    d19_f1.append(float(rep.split('\n')[3].split('      ')[4].strip()))
    d25_pre.append(float(rep.split('\n')[4].split('      ')[2].strip()))
    d25_rec.append(float(rep.split('\n')[4].split('      ')[3].strip()))
    d25_f1.append(float(rep.split('\n')[4].split('      ')[4].strip()))
    d45_pre.append(float(rep.split('\n')[5].split('      ')[2].strip()))
    d45_rec.append(float(rep.split('\n')[5].split('      ')[3].strip()))
    d45_f1.append(float(rep.split('\n')[5].split('      ')[4].strip()))
    i = i+1
    
print("average accuracy :{}".format(np.average(acc_rf)))
print("\n\n classification_report average\n")
print('                    precision    recall    f1-score   \n\n         0.00       {:.4f}      {:.4f}      {:.4f}        \n         0.19       {:.4f}      {:.4f}      {:.4f}        \n         2.50       {:.4f}      {:.4f}      {:.4f}      \n         4.50       {:.4f}      {:.4f}      {:.4f}        \n\n'.
      format(np.average(d0_pre), np.average(d0_rec), np.average(d0_f1), np.average(d19_pre), np.average(d19_rec), np.average(d19_f1), np.average(d25_pre), np.average(d25_rec), np.average(d25_f1), np.average(d45_pre), np.average(d45_rec),np.average(d45_f1)))


________________ ** 1 ** ____________________
[[26  0  0  0]
 [ 0 48  0  0]
 [ 0  0 25  0]
 [ 0  0  0 82]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        26
        0.19       1.00      1.00      1.00        48
         2.5       1.00      1.00      1.00        25
         4.5       1.00      1.00      1.00        82

    accuracy                           1.00       181
   macro avg       1.00      1.00      1.00       181
weighted avg       1.00      1.00      1.00       181

1.0
________________ ** 2 ** ____________________
[[31  0  0  0]
 [ 0 40  0  0]
 [ 0  0 27  0]
 [ 0  0  0 83]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        31
        0.19       1.00      1.00      1.00        40
         2.5       1.00      1.00      1.00        27
         4.5       1.00      1.00      1.00        83

    accuracy                           1.00       181
   macro avg       1.

#  NAÏVE BAYES

In [14]:
model_nb =  GaussianNB(priors=None)

In [15]:
i = 1
acc_nb = []
d0_pre =[]
d0_rec=[]
d0_f1 =  []
d19_pre = []
d19_rec =[]
d19_f1=[]
d25_pre =[]
d25_rec=[]
d25_f1=[]
d45_pre=[]
d45_rec =[]
d45_f1=[]
for train_index, test_index in kf5sh.split(x):
#     print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = x[train_index], x[test_index]
    Y_train, Y_test = y[train_index], y[test_index]
    model_nb.fit(X_train,Y_train)
    y_pred = model_nb.predict(X_test)
    print("________________ ** {} ** ____________________".format(i))
    print(confusion_matrix(Y_test,y_pred))
    print(classification_report(Y_test,y_pred))
    print(accuracy_score(Y_test, y_pred))
    acc_nb.append(accuracy_score(Y_test, y_pred))
    rep = classification_report(Y_test,y_pred)
    d0_pre.append(float(rep.split('\n')[2].split('      ')[2].strip()))
    d0_rec.append(float(rep.split('\n')[2].split('      ')[3].strip()))
    d0_f1.append(float(rep.split('\n')[2].split('      ')[4].strip()))
    d19_pre.append(float(rep.split('\n')[3].split('      ')[2].strip()))
    d19_rec.append(float(rep.split('\n')[3].split('      ')[3].strip()))
    d19_f1.append(float(rep.split('\n')[3].split('      ')[4].strip()))
    d25_pre.append(float(rep.split('\n')[4].split('      ')[2].strip()))
    d25_rec.append(float(rep.split('\n')[4].split('      ')[3].strip()))
    d25_f1.append(float(rep.split('\n')[4].split('      ')[4].strip()))
    d45_pre.append(float(rep.split('\n')[5].split('      ')[2].strip()))
    d45_rec.append(float(rep.split('\n')[5].split('      ')[3].strip()))
    d45_f1.append(float(rep.split('\n')[5].split('      ')[4].strip()))
    i = i+1
    
print("average accuracy :{}".format(np.average(acc_nb)))
print("\n\n classification_report average\n")
print('                    precision    recall    f1-score   \n\n         0.00       {:.4f}      {:.4f}      {:.4f}        \n         0.19       {:.4f}      {:.4f}      {:.4f}        \n         2.50       {:.4f}      {:.4f}      {:.4f}      \n         4.50       {:.4f}      {:.4f}      {:.4f}        \n\n'.
      format(np.average(d0_pre), np.average(d0_rec), np.average(d0_f1), np.average(d19_pre), np.average(d19_rec), np.average(d19_f1), np.average(d25_pre), np.average(d25_rec), np.average(d25_f1), np.average(d45_pre), np.average(d45_rec),np.average(d45_f1)))


________________ ** 1 ** ____________________
[[26  0  0  0]
 [ 0 48  0  0]
 [ 0  0 25  0]
 [ 0  2  0 80]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        26
        0.19       0.96      1.00      0.98        48
         2.5       1.00      1.00      1.00        25
         4.5       1.00      0.98      0.99        82

    accuracy                           0.99       181
   macro avg       0.99      0.99      0.99       181
weighted avg       0.99      0.99      0.99       181

0.988950276243094
________________ ** 2 ** ____________________
[[31  0  0  0]
 [ 2 38  0  0]
 [ 0  0 27  0]
 [ 4  2  0 77]]
              precision    recall  f1-score   support

         0.0       0.84      1.00      0.91        31
        0.19       0.95      0.95      0.95        40
         2.5       1.00      1.00      1.00        27
         4.5       1.00      0.93      0.96        83

    accuracy                           0.96       181
   macr

# SUMMARY

In [16]:
print("_______________________________________ACCURACY TABLE______________________________________________________")
print("||________________________SVM__________________||____________________{}____________________||".format(np.average(acc_svm)))
print("||__________________RANDOM_FOREST______________||____________________{}____________________||".format(np.average(acc_rf)))
print("||________________________NB___________________||____________________{}____________________||".format(np.average(acc_nb)))

_______________________________________ACCURACY TABLE______________________________________________________
||________________________SVM__________________||____________________0.9944567219152856____________________||
||__________________RANDOM_FOREST______________||____________________0.9966666666666667____________________||
||________________________NB___________________||____________________0.9756169429097605____________________||
