In [31]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, KFold, cross_val_score, cross_validate

In [32]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.svm import SVC

In [33]:
from sklearn.model_selection import cross_val_predict

In [34]:
from sklearn.metrics import make_scorer, accuracy_score, precision_score, recall_score, f1_score

In [35]:
data = pd.read_csv('../data/std_data.csv')
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].apply(lambda x: str(x)).values

In [36]:
kf5sh = KFold(n_splits= 5, shuffle= True, random_state= 20)

In [37]:
model_svm = SVC(C=3.0, kernel='linear')

In [38]:
scoring = {'accuracy' : make_scorer(accuracy_score), 
           'precision' : make_scorer(precision_score),
           'recall' : make_scorer(recall_score), 
           'f1_score' : make_scorer(f1_score)}

In [39]:
scores = cross_validate(model_svm, x, y, cv =kf5sh, scoring=scores)

ValueError: scoring should either be a single string or callable for single metric evaluation or a list/tuple of strings or a dict of scorer name mapped to the callable for multiple metric evaluation. Got array([1.        , 1.        , 1.        , 0.99444444, 0.98888889]) of type <class 'numpy.ndarray'>

In [27]:
scores

array([1.        , 1.        , 1.        , 0.99444444, 0.98888889])

In [28]:
np.average(scores)

0.9966666666666667

In [137]:
i = 1
acc_svm = []
d0_pre =[]
d0_rec=[]
d0_f1 =  []
d19_pre = []
d19_rec =[]
d19_f1=[]
d25_pre =[]
d25_rec=[]
d25_f1=[]
d45_pre=[]
d45_rec =[]
d45_f1=[]
for train_index, test_index in kf5sh.split(x):
#     print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = x[train_index], x[test_index]
    Y_train, Y_test = y[train_index], y[test_index]
    model_svm.fit(X_train,Y_train)
    y_pred = model_svm.predict(X_test)
    print("________________ ** {} ** ____________________".format(i))
    print(confusion_matrix(Y_test,y_pred))
    print(classification_report(Y_test,y_pred))
    rep = classification_report(Y_test,y_pred)
    print(accuracy_score(Y_test, y_pred))
    acc_svm.append(accuracy_score(Y_test, y_pred))
    d0_pre.append(float(rep.split('\n')[2].split('      ')[2].strip()))
    d0_rec.append(float(rep.split('\n')[2].split('      ')[3].strip()))
    d0_f1.append(float(rep.split('\n')[2].split('      ')[4].strip()))
    d19_pre.append(float(rep.split('\n')[3].split('      ')[2].strip()))
    d19_rec.append(float(rep.split('\n')[3].split('      ')[3].strip()))
    d19_f1.append(float(rep.split('\n')[3].split('      ')[4].strip()))
    d25_pre.append(float(rep.split('\n')[4].split('      ')[2].strip()))
    d25_rec.append(float(rep.split('\n')[4].split('      ')[3].strip()))
    d25_f1.append(float(rep.split('\n')[4].split('      ')[4].strip()))
    d45_pre.append(float(rep.split('\n')[5].split('      ')[2].strip()))
    d45_rec.append(float(rep.split('\n')[5].split('      ')[3].strip()))
    d45_f1.append(float(rep.split('\n')[5].split('      ')[4].strip()))
    i = i+1
    
print("average accuracy :{}".format(np.average(acc_svm)))
print("\n\n classification_report average\n")
print('                    precision    recall    f1-score   \n\n         0.00       {:.4f}      {:.4f}      {:.4f}        \n         0.19       {:.4f}      {:.4f}      {:.4f}        \n         2.50       {:.4f}      {:.4f}      {:.4f}      \n         4.50       {:.4f}      {:.4f}      {:.4f}        \n\n'.
      format(np.average(d0_pre), np.average(d0_rec), np.average(d0_f1), np.average(d19_pre), np.average(d19_rec), np.average(d19_f1), np.average(d25_pre), np.average(d25_rec), np.average(d25_f1), np.average(d45_pre), np.average(d45_rec),np.average(d45_f1)))


________________ ** 1 ** ____________________
[[26  0  0  0]
 [ 0 48  0  0]
 [ 0  0 25  0]
 [ 0  0  0 82]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        26
        0.19       1.00      1.00      1.00        48
         2.5       1.00      1.00      1.00        25
         4.5       1.00      1.00      1.00        82

    accuracy                           1.00       181
   macro avg       1.00      1.00      1.00       181
weighted avg       1.00      1.00      1.00       181

1.0
________________ ** 2 ** ____________________
[[31  0  0  0]
 [ 0 40  0  0]
 [ 0  0 27  0]
 [ 0  0  0 83]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        31
        0.19       1.00      1.00      1.00        40
         2.5       1.00      1.00      1.00        27
         4.5       1.00      1.00      1.00        83

    accuracy                           1.00       181
   macro avg       1.

In [95]:
type(cls_rep)

list

In [99]:
d0_pre, np.average(d0_pre)

([1.0, 1.0, 1.0, 1.0, 1.0], 1.0)

In [100]:
d0_rec, np.average(d0_rec)

([1.0, 1.0, 1.0, 0.97, 0.94], 0.982)

In [98]:
d0_f1

[1.0, 1.0, 1.0, 0.99, 0.97]

In [102]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.20, random_state=42)

In [103]:
model = SVC(C=3.0, kernel='linear')

In [104]:
model.fit(x_train,y_train)

SVC(C=3.0, kernel='linear')

In [105]:
y_pred = model.predict(x_test)

In [106]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[30  0  0  1]
 [ 0 43  0  0]
 [ 0  0 27  0]
 [ 0  0  0 80]]
              precision    recall  f1-score   support

         0.0       1.00      0.97      0.98        31
        0.19       1.00      1.00      1.00        43
         2.5       1.00      1.00      1.00        27
         4.5       0.99      1.00      0.99        80

    accuracy                           0.99       181
   macro avg       1.00      0.99      0.99       181
weighted avg       0.99      0.99      0.99       181

0.994475138121547


In [107]:
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n         0.0       1.00      0.97      0.98        31\n        0.19       1.00      1.00      1.00        43\n         2.5       1.00      1.00      1.00        27\n         4.5       0.99      1.00      0.99        80\n\n    accuracy                           0.99       181\n   macro avg       1.00      0.99      0.99       181\nweighted avg       0.99      0.99      0.99       181\n'

In [90]:
int(classification_report(y_test,y_pred).split('\n')[5].split('      ')[3].strip())

ValueError: invalid literal for int() with base 10: '0.46'

In [92]:
f ='3.5'

In [93]:
int(f)

ValueError: invalid literal for int() with base 10: '3.5'

In [ ]:
d0_pre =[]
d0_rec=[]
d0_f1 =  []
d19_pre = []
d19_rec =[]
d19_f1=[]
d25_pre =[]
d25_rec=[]
d25_f1=[]
d45_pre=[]
d45_rec =[]
d45_f1=[]
