In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [2]:
from sklearn.naive_bayes import GaussianNB

In [3]:
data = pd.read_csv('../data/std_data.csv')
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].apply(lambda x: str(x)).values

In [4]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.20, random_state=42)

In [5]:
classifier =  GaussianNB(priors=None)

In [6]:
classifier.fit(x_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [7]:
y_pred = classifier.predict(x_test)

In [8]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[28  0  3  0]
 [ 2 41  0  0]
 [ 0  0 27  0]
 [ 0  1  0 79]]
              precision    recall  f1-score   support

         0.0       0.93      0.90      0.92        31
        0.19       0.98      0.95      0.96        43
         2.5       0.90      1.00      0.95        27
         4.5       1.00      0.99      0.99        80

    accuracy                           0.97       181
   macro avg       0.95      0.96      0.96       181
weighted avg       0.97      0.97      0.97       181

0.9668508287292817


In [9]:
# applying pca

In [10]:
from sklearn.decomposition import PCA

In [11]:
pca = PCA(n_components= None)

In [12]:
x_t1 = pca.fit_transform(x_train)

In [13]:
x_te1 = pca.fit_transform(x_test)

In [14]:
ext = pca.explained_variance_ratio_

In [15]:
print(ext, ext.shape, end = '\n')

[3.74845487e-01 1.75552068e-01 1.08254268e-01 8.57308929e-02
 4.60100395e-02 4.26144287e-02 3.07761065e-02 2.82503173e-02
 2.43563132e-02 2.26478322e-02 1.44042754e-02 9.73960811e-03
 9.20989728e-03 5.79699459e-03 3.71783506e-03 2.86974861e-03
 2.70697516e-03 2.57204643e-03 1.93937371e-03 1.68633762e-03
 1.20686935e-03 1.12887418e-03 8.80020121e-04 7.88254077e-04
 5.12406684e-04 3.88212762e-04 3.12086209e-04 2.33449495e-04
 2.23410089e-04 2.00349801e-04 1.42202398e-04 1.15375468e-04
 7.79892735e-05 5.48658729e-05 3.25349622e-05 2.01090785e-05
 1.64757119e-06 2.58416424e-07 1.07338627e-07 7.20907067e-08
 4.18793112e-08 1.59383308e-08 1.24851127e-09 2.83316621e-10
 1.35875741e-10] (45,)


In [16]:
print(pca.explained_variance_)
print(pca.explained_variance_.shape)

[1.85636774e+01 8.69396079e+00 5.36113513e+00 4.24569775e+00
 2.27858027e+00 2.11041758e+00 1.52414190e+00 1.39905587e+00
 1.20621098e+00 1.12160094e+00 7.13350785e-01 4.82339922e-01
 4.56106764e-01 2.87087723e-01 1.84120373e-01 1.42120125e-01
 1.34059007e-01 1.27376858e-01 9.60446615e-02 8.35134172e-02
 5.97684490e-02 5.59058516e-02 4.35817162e-02 3.90371364e-02
 2.53761955e-02 1.92256723e-02 1.54556154e-02 1.15612466e-02
 1.10640596e-02 9.92203242e-03 7.04236686e-03 5.71380221e-03
 3.86230531e-03 2.71715253e-03 1.61124667e-03 9.95872856e-04
 8.15935665e-05 1.27976975e-05 5.31578934e-06 3.57018737e-06
 2.07401196e-06 7.89322644e-07 6.18307042e-08 1.40308435e-08
 6.72904841e-09]
(45,)


In [17]:
# Setting the pc = 10

In [18]:
pca = PCA(n_components= 10)
x_t1 = pca.fit_transform(x_train)
x_te1 = pca.fit_transform(x_test)
classifier =  GaussianNB(priors=None)
classifier.fit(x_t1, y_train)
y_pred = classifier.predict(x_te1)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[17  3  2  9]
 [13 25  4  1]
 [ 0  0 27  0]
 [ 3  6  0 71]]
              precision    recall  f1-score   support

         0.0       0.52      0.55      0.53        31
        0.19       0.74      0.58      0.65        43
         2.5       0.82      1.00      0.90        27
         4.5       0.88      0.89      0.88        80

    accuracy                           0.77       181
   macro avg       0.74      0.75      0.74       181
weighted avg       0.77      0.77      0.77       181

0.7734806629834254


In [19]:
pca = PCA(n_components= 25)
x_t1 = pca.fit_transform(x_train)
x_te1 = pca.fit_transform(x_test)
classifier =  GaussianNB(priors=None)
classifier.fit(x_t1, y_train)
y_pred = classifier.predict(x_te1)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[18  7  3  3]
 [11 28  2  2]
 [ 0  0 27  0]
 [13  5  0 62]]
              precision    recall  f1-score   support

         0.0       0.43      0.58      0.49        31
        0.19       0.70      0.65      0.67        43
         2.5       0.84      1.00      0.92        27
         4.5       0.93      0.78      0.84        80

    accuracy                           0.75       181
   macro avg       0.72      0.75      0.73       181
weighted avg       0.77      0.75      0.75       181

0.7458563535911602


In [20]:
pca = PCA(n_components= 45)
x_t1 = pca.fit_transform(x_train)
x_te1 = pca.fit_transform(x_test)
classifier =  GaussianNB(priors=None)
classifier.fit(x_t1, y_train)
y_pred = classifier.predict(x_te1)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[24  2  3  2]
 [ 6 33  2  2]
 [ 0  0 27  0]
 [10  3  0 67]]
              precision    recall  f1-score   support

         0.0       0.60      0.77      0.68        31
        0.19       0.87      0.77      0.81        43
         2.5       0.84      1.00      0.92        27
         4.5       0.94      0.84      0.89        80

    accuracy                           0.83       181
   macro avg       0.81      0.84      0.82       181
weighted avg       0.85      0.83      0.84       181

0.8342541436464088


In [22]:
pca = PCA(n_components= 40)
x_t1 = pca.fit_transform(x_train)
x_te1 = pca.fit_transform(x_test)
classifier =  GaussianNB(priors=None)
classifier.fit(x_t1, y_train)
y_pred = classifier.predict(x_te1)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[24  2  3  2]
 [ 6 33  2  2]
 [ 0  0 27  0]
 [11  4  0 65]]
              precision    recall  f1-score   support

         0.0       0.59      0.77      0.67        31
        0.19       0.85      0.77      0.80        43
         2.5       0.84      1.00      0.92        27
         4.5       0.94      0.81      0.87        80

    accuracy                           0.82       181
   macro avg       0.80      0.84      0.81       181
weighted avg       0.84      0.82      0.83       181

0.8232044198895028
