In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

In [2]:
data = pd.read_csv('../data/std_data.csv')

In [3]:
data

gx_mean  gx_median  gx_variance    gx_fft  gx_spec_energy   gy_mean  \
0    0.046215   0.058430    -0.220840 -0.229310       -0.220605  0.385255   
1   -0.174583  -0.183538    -0.237830 -0.446876       -0.237550  0.400423   
2   -0.209093  -0.218446    -0.243878 -0.504801       -0.243634  0.411072   
3   -0.223293  -0.183240    -0.233575 -0.462391       -0.233330  0.415867   
4   -0.242859  -0.159073    -0.224825 -0.427087       -0.224536  0.413581   
..        ...        ...          ...       ...             ...       ...   
897 -0.083690  -0.119329    -0.038897  0.042016       -0.038763 -7.071246   
898 -0.141768  -0.117586    -0.001722  0.022061       -0.001547 -7.071041   
899  0.685436   0.033866     2.909161  2.191753        2.909752 -6.675688   
900  0.752242  -0.149132     2.838121  2.089799        2.836993 -4.104739   
901 -0.152722  -0.354915     0.223914 -0.364357       -0.020152 -1.916145   

     gy_median  gy_variance    gy_fft  gy_spec_energy  ...  wy_median  \
0     0.373062    -0.237299  0.359702       -0.236724  ...  -1.275804   
1     0.388720    -0.237515  0.384871       -0.236948  ...   0.784026   
2     0.398077    -0.237819  0.392210       -0.237252  ...   0.566364   
3     0.403806    -0.237943  0.393427       -0.237376  ...   0.327466   
4     0.404761    -0.237771  0.399360       -0.237204  ...   1.851104   
..         ...          ...       ...             ...  ...        ...   
897  -7.061143    -0.235080  0.407856       -0.234513  ...  -0.747256   
898  -7.055827    -0.235851  0.383282       -0.235285  ...  -4.731489   
899  -7.023176     1.615553  1.448012        1.617483  ...  -0.314639   
900  -4.426905    15.740210 -0.700166       15.747353  ...   0.624177   
901  -1.669206     0.977980 -4.448108        0.358110  ...   0.092497   

     wy_variance    wy_fft  wy_spec_energy   wz_mean  wz_median  wz_variance  \
0      -0.241437 -0.421834       -0.241703 -0.526301  -0.595596    -0.229148   
1      -0.169742 -0.009689       -0.165206 -0.229242  -0.533358    -0.244148   
2      -0.187077 -0.017944       -0.188066  0.004644  -0.136590    -0.266644   
3      -0.019173  0.562431       -0.019202 -0.515430  -0.517798    -0.288882   
4       0.544371  1.628924        0.547799 -0.399662  -0.821209    -0.250318   
..           ...       ...             ...       ...        ...          ...   
897     1.618458  2.067892        1.664508 -0.186423   0.525233     0.023756   
898     2.777027  2.503986        2.785224 -0.218506   1.494668     0.346958   
899     8.599137  1.848900        8.599015 -4.666282   0.707435     4.673772   
900     8.357835  3.236073        8.378800 -2.230325   0.305455     4.940829   
901     3.094755  1.936148        1.321408  3.389331   2.145211     0.932688   

       wz_fft  wz_spec_energy  label  
0   -0.366775       -0.229310    0.0  
1   -0.506583       -0.244439    0.0  
2   -0.583725       -0.265907    0.0  
3   -0.388326       -0.287477    0.0  
4   -0.305767       -0.250568    0.0  
..        ...             ...    ...  
897  0.687085        0.023392    2.5  
898  1.014308        0.345634    2.5  
899  3.817541        4.707787    2.5  
900  3.491547        5.007725    2.5  
901  1.030752        0.289102    2.5  

[902 rows x 46 columns]

In [11]:
x = data.iloc[:,:-1].values

In [12]:
x

array([[ 0.04621491,  0.05842975, -0.22083982, ..., -0.22914835,
        -0.36677491, -0.22930991],
       [-0.17458333, -0.18353847, -0.23783025, ..., -0.24414803,
        -0.50658303, -0.24443851],
       [-0.20909349, -0.21844634, -0.24387775, ..., -0.26664441,
        -0.58372546, -0.26590708],
       ...,
       [ 0.68543597,  0.03386595,  2.90916055, ...,  4.67377196,
         3.81754061,  4.70778694],
       [ 0.75224214, -0.14913184,  2.83812149, ...,  4.94082851,
         3.49154685,  5.00772549],
       [-0.15272177, -0.35491522,  0.22391389, ...,  0.93268846,
         1.03075248,  0.28910169]])

In [37]:
y = data.iloc[:,-1].apply(lambda x: str(x)).values

In [38]:
type(y[0])

str

In [39]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.20, random_state=0)

In [40]:
x_train.shape

(721, 45)

In [41]:
x_test.shape

(181, 45)

In [42]:
y_train.shape

(721,)

In [43]:
y_train.shape, y_test.shape

((721,), (181,))

In [44]:
np.unique(y_test)

array(['0.0', '0.19', '2.5', '4.5'], dtype=object)

In [45]:
type(y_train[0])

str

In [46]:
#  trainig the classifier

In [47]:
classifier = RandomForestClassifier(n_estimators=30,criterion='entropy',max_depth=10,max_features='sqrt',max_leaf_nodes=None,min_samples_split=8)

In [48]:
classifier.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=10, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=8,
                       min_weight_fraction_leaf=0.0, n_estimators=30,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [49]:
y_pred = classifier.predict(x_test)

In [50]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[20  0  0  0]
 [ 0 44  0  1]
 [ 0  0 27  0]
 [ 0  0  0 89]]


In [51]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[20  0  0  0]
 [ 0 44  0  1]
 [ 0  0 27  0]
 [ 0  0  0 89]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        20
        0.19       1.00      0.98      0.99        45
         2.5       1.00      1.00      1.00        27
         4.5       0.99      1.00      0.99        89

    accuracy                           0.99       181
   macro avg       1.00      0.99      1.00       181
weighted avg       0.99      0.99      0.99       181

0.994475138121547
